name: branch workflow

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
      lastName:
        required: true
  repository_dispatch:
    types: [pull-request-event]

env:
  AWS_REGION: "eu-west-2"

permissions:
  id-token: write
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Run stuff
        run: echo "this is working for me"

      - name: echo message
        run: |
          echo "${{ github.event.inputs.name }}"
          echo "${{ github.event.inputs.lastName }}"
