name: branch workflow 4

on:
  workflow_dispatch:
    inputs:
      dataNotJson:
        type: string
        required: true
      testValue:
        type: string
        required: true
  repository_dispatch:
    types: [pull-request-event]

env:
  AWS_REGION: "eu-west-2"

permissions:
  id-token: write
  contents: read

jobs:
  runTerraform:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: Run stuff
        run: echo "this is working for me"

      - name: Generate .tfvars File
        run: |

          echo "-----testValue-----"
          testValue="${{ github.event.inputs.testValue }}"
          echo "$testValue"
          echo "-----testValue-----"

          echo "-----environment-----"
          extra="$(echo "$testValue" | jq -r '.environment')"
          echo "$extra"
          echo "-----environment-----"


          encodedJson="${{ github.event.inputs.dataNotJson }}"
          echo=$encodedJson

          json=$(echo "${{ github.event.inputs.dataNotJson }}" | base64 -d)

          echo "$json"

          environment="$(echo "$json" | jq -r '.environment')"
          echo "-----environment-----"
          echo $environment
          echo "-----environment-----"
