name: branch workflow 2

on:
  workflow_dispatch:
    inputs:
      data:
        type: string
        required: true
  repository_dispatch:
    types: [pull-request-event]

env:
  AWS_REGION: "eu-west-2"

permissions:
  id-token: write
  contents: read

jobs:
  runTerraform:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: Run stuff
        run: echo "this is working for me"

      - name: Generate .tfvars File
        run: |
          echo "${{ github.event.inputs.data }}"
          echo "${{ fromJson(github.event.inputs.data).environment }}"
          echo "${{ fromJson(github.event.inputs.data).alternate_contacts }}"

          echo "-----------some extra stuff"

          environment="${{ fromJson(github.event.inputs.data).environment }}"
          avm_aws_account_name="${{ fromJson(github.event.inputs.data).avm_aws_account_name }}"
          avm_aws_account_email="${{ fromJson(github.event.inputs.data).avm_aws_account_email }}"
          avm_aws_account_alias="${{ fromJson(github.event.inputs.data).avm_aws_account_alias }}"
          avm_org_ou_name="${{ fromJson(github.event.inputs.data).avm_org_ou_name }}"
          alternate_contacts="${{ toJson(fromJson(github.event.inputs.data).alternate_contacts) }}"
          avm_subdomain="${{ toJson(fromJson(github.event.inputs.data).avm_subdomain) }}"
          auto_shutdown_enabled="${{ fromJson(github.event.inputs.data).auto_shutdown_enabled }}"

          echo $environment
