name: branch workflow 2

on:
  workflow_dispatch:
    inputs:
      data:
        type: string
        required: true
  repository_dispatch:
    types: [pull-request-event]

env:
  AWS_REGION: "eu-west-2"

permissions:
  id-token: write
  contents: read

jobs:
  runTerraform:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: Run stuff
        run: echo "this is working for me"

      - name: Generate .tfvars File
        run: |
          echo "${{ github.event.inputs.data }}"

          environment="${{ fromJson(github.event.inputs.data).environment }}"

          echo $environment
