name: reusable_workflow_inputs_caller

on:
  pull_request:
  workflow_dispatch:
    inputs:
      vend_secondary_virtual_network_size:
        description: Secondary Region Virtual Network Size
        type: choice
        required: false
        options:
          - small
          - medium
          - large
          - x-small
          - x-large

jobs:
  set:
    runs-on: ubuntu-latest
    outputs:
      vend_bypass_approval_step: ${{ steps.set.outputs.vend_bypass_approval_step }}
    steps:
      - name: Set
        id: set
        run: |
          vend_bypass_approval_step=$([ -n "${{ github.event.inputs.vend_secondary_virtual_network_size }}" ] && echo "true" || echo "false")
          output='OUTPUT'
          echo "vend_bypass_approval_step=$vend_bypass_approval_step" >> "$GITHUB_OUTPUT"

  get:
    runs-on: ubuntu-latest
    needs: set
    steps:
      - name: Get
        run: |
          {
            echo '```yml'
            echo 'inputs.input: '
            echo 'steps.set.outputs.output: '
            echo '```'
          } | tee -a "$GITHUB_STEP_SUMMARY"

  callee:
    name: callee
    needs: [set]
    uses: ./.github/workflows/ci-reusable-workflow-inputs-callee.yml
    with:
      vend_bypass_approval_step: ${{ needs.set.outputs.vend_bypass_approval_step }}
