name: Manually triggered workflow
on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        required: true
      name:
        required: true
      emailAddress:
        required: true
      workloadShortName:
        required: true
      opsDlMail:
        required: true
      securityDlMail:
        required: true
      roles:
        required: true
      dnsSubDomains:
        required: true
      sesSubDomains:
        required: true
      securityClass:
        required: true

permissions: write-all

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      # - run: |
      #     echo "Hello ${{ github.event.inputs.alternate_contacts }}!"
      #     echo "- in ${{ github.event.inputs.home }}!"

      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Make the script files executable
        run: chmod +x scripts/build-tfvars-file.sh

      - name: Run a script
        run: ./scripts/build-tfvars-file.sh

      - name: check file
        run: |
          echo "-----the file-----"
          filename="etc/env_eu-west-2_some_environment.tfvars"
          value="`cat $filename`"
          echo "$value"

      - name: echo values
        run: |
          echo "${{ github.event.inputs.environment }}"
          echo "${{ github.event.inputs.name }}"
          echo "${{ github.event.inputs.emailAddress }}"
          echo "${{ github.event.inputs.workloadShortName }}"
          echo "${{ github.event.inputs.opsDlMail }}"
          echo "${{ github.event.inputs.securityDlMail }}"
          echo "${{ github.event.inputs.roles }}"
          echo "${{ github.event.inputs.dnsSubDomains }}"
          echo "${{ github.event.inputs.sesSubDomains }}"
          echo "${{ github.event.inputs.securityClass }}"

      - name: Make the script files executable
        run: chmod +x scripts/my-script.sh

      - name: Run a script
        run: ./scripts/my-script.sh "${{ github.event.inputs.name }}"
