name: Manually triggered workflow
on:
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "Mona the Octocat"
      home:
        description: "location"
        required: false
        default: "The Octoverse"
      alternate_contacts:
        description: "location"
        required: false
        default: "The Octoverse"

permissions: write-all

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.alternate_contacts }}!"
          echo "- in ${{ github.event.inputs.home }}!"

      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Make the script files executable
        run: chmod +x scripts/build-tfvars-file.sh

      - name: Run a script
        run: ./scripts/build-tfvars-file.sh

      - name: check file
        run: |
          echo "-----one the file-----"
          filename="etc/env_eu-west-2_some_environment.tfvars"
          value="`cat $filename`"
          echo "$value"

      # - name: Make the script files executable
      #   run: chmod +x scripts/my-script.sh

      # - name: Run a script
      #   run: ./scripts/my-script.sh
