name: main workflow 2

on:
  workflow_dispatch:
  repository_dispatch:
    types: [main-event-2]

env:
  AWS_REGION: "eu-west-2"

permissions: write-all

jobs:
  main-run:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: Generate .tfvars File
        run: gh workflow run branch-workflow-2.yaml --ref extra-branch -f data='${{toJson(github.event.client_payload)}}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
