name: main workflow

on:
  workflow_dispatch:
  repository_dispatch:
    types: [main-event]

env:
  AWS_REGION: "eu-west-2"

permissions:
  id-token: write
  contents: read

jobs:
  test-step:
    runs-on: ubuntu-latest
    steps:
      - name: Run stuff
        run: echo "this is working"
