name: main workflow 4

on:
  workflow_dispatch:
  repository_dispatch:
    types: [main-event]

env:
  AWS_REGION: "eu-west-2"

permissions: write-all

jobs:
  main-run:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: Generate .tfvars File
        run: |
          echo "${{ github.event.client_payload.name }}"
          echo gh workflow run branch-workflow-4.yaml --ref extra-branch -f dataNotJson='${{github.event.client_payload}}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
