name: New workflow
on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        required: true
      name:
        required: false
      size:
        description: Secondary Region Virtual Network Size
        type: choice
        default: small
        options:
          - small
          - medium
          - large
          - x-small
          - x-large

permissions: write-all

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: echo values
        run: |
          hasName=$([ -n "${{ github.event.inputs.name }}" ] && echo "true" || echo "false")
          echo $hasName
          echo "${{ github.event.inputs.environment }}"
          echo "${{ github.event.inputs.name }}"
          echo "${{ github.event.inputs.size }}"
