name: New workflow
on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        required: true
      name:
        required: false
      size:
        description: Secondary Region Virtual Network Size
        type: choice
        options:
          - small
          - medium
          - large
          - x-small
          - x-large

env:
  environment: ${{ inputs.environment }}
  name: ${{ inputs.name }}
  size: ${{ inputs.size }}

permissions: write-all

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: echo out env vars
        run: |
          echo "ENVIRONMENT=${{ env.environment }}"
          echo "NAME=${{ env.name }}"
          echo "SIZE=${{ env.size }}"

      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "NAME=${{ inputs.name }}" >> $GITHUB_ENV
          echo "SIZE=${{ inputs.size }}" >> $GITHUB_ENV

  sub-workflow:
    uses: ./.github/workflows/new-sub-workflow.yaml
    with:
      environment: "${{ inputs.environment }}"
      name: ${{ inputs.name }}
      size: ${{ inputs.size }}
