name: New Sub Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      name:
        required: false
        type: string
      size:
        required: true
        type: string

permissions: write-all

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: echo values
        env:
          environment: ${{ inputs.environment }}
          name: ${{ inputs.name }}
          size: ${{ inputs.size }}
        run: |
          echo "ENVIRONMENT="${{ env.environment }}""
          echo "NAME="${{ env.name }}""
          echo "SIZE="${{ env.size }}""

          echo "ENVIRONMENT="${{ inputs.environment }}""
          echo "NAME="${{ inputs.name }}""
          echo "SIZE="${{ inputs.size }}""
