name: New workflow
on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        required: true
      name:
        required: false
      size:
        description: Secondary Region Virtual Network Size
        type: choice
        options:
          - small
          - medium
          - large
          - x-small
          - x-large

permissions: write-all

jobs:
  sub-workflow:
    uses: ./.github/workflows/new-sub-workflow.yaml
    with:
      environment: ${{ inputs.environment }}
      name: ${{ inputs.name }}
      size: ${{ inputs.size }}
