name: New workflow
on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        required: true
      name:
        required: false

permissions: write-all

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: echo values
        run: |
          if [ -z "${{ github.event.inputs.name }}" ]; then
            echo "Name is not provided"
          else
            echo "Name is provided: ${{ github.event.inputs.name }}"
          fi
          echo "${{ github.event.inputs.environment }}"
          echo "${{ github.event.inputs.name }}"
