name: New workflow
on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        required: true
      name:
        required: false
      size:
        description: Secondary Region Virtual Network Size
        type: choice
        options:
          - small
          - medium
          - large
          - x-small
          - x-large

permissions: write-all

jobs:
  say_hello:
    runs-on: ubuntu-latest
    outputs:
      hasName: ${{ steps.calculate-has-name.outputs.hasName }}

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: calculate-has-name
        id: calculate-has-name
        run: |
          echo  "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.environment }}!"

          hasName=$([ -n "${{ github.event.inputs.name }}" ] && echo "true" || echo "false")
            echo "hasName=$hasName"
            echo "$hasName"
          echo "hasName=$hasName" >> "$GITHUB_OUTPUT"

  sub-workflow:
    needs: say_hello
    uses: ./.github/workflows/new-sub-workflow.yaml
    with:
      environment: ${{ inputs.environment }}
      name: ${{ inputs.name }}
      data: ${{needs.say_hello.outputs.hasName}}
