name: Skip step checker

on:
  workflow_dispatch:
    inputs:
      booleanOne:
        type: boolean
        required: true
      booleanTwo:
        type: boolean
        required: true
      vend_bypass_approval_step:
        type: boolean
        required: true

jobs:
  approvalStep:
    if: ${{inputs.vend_bypass_approval_step == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: approval step
        run: |
          echo "perform approval step"

  DeployTerraform:
    needs: approvalStep
    if: always() && (needs.approvalStep.result == 'success' || needs.approvalStep.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Hello World
        run: |
          echo "Deploying terraform"
