name: Test Validation of inputs

on:
  workflow_dispatch:
    inputs:
      vend_workload_short_name:
        description: Workload Short Name
        type: string
        required: true
      vend_environment_type:
        description: Environment Type
        type: choice
        required: true
        options:
          - Sandbox
          - Dev
          - Test
          - Preprod
          - Prod
          - Tooling
      vend_environment_name:
        description: Environment Name
        type: string
        required: false
      vend_vpc_size:
        description: VPC Size
        type: choice
        required: true
        options:
          - Small
          - Medium
          - Large
          - X-Large
      vend_vpc_requestor:
        description: VPC Requestor
        type: string
        required: true
      groupsToAdd:
        type: string
        required: false
        default: "[]"
      groupsToRemove:
        type: string
        required: false
        default: "[]"
      userPrincipalName:
        type: string
        required: true
      definition:
        type: string
        required: false
        default: "{}"

jobs:
  First_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: powershell test
        shell: pwsh
        env:
          VEND_VPC_REQUESTOR: ${{ inputs.vend_vpc_requestor }}
        run: |
          $vend_vpc_requestor = ${env:VEND_VPC_REQUESTOR}
          Write-Host "VEND_VPC_REQUESTOR: ${env:VEND_VPC_REQUESTOR}"

      - name: powershellActionTest
        uses: azure/powershell@v2
        env:
          GROUPS_TO_ADD: ${{ inputs.groupsToAdd }}
          GROUPS_TO_REMOVE: ${{ inputs.groupsToRemove }}
          USER_PRINCIPAL_NAME: ${{ inputs.userPrincipalName }}
          DEFINITION: ${{ inputs.definition }}
        with:
          inlineScript: |

            Write-Host "Running PowerShell script with GROUPS_TO_ADD: ${env:VEND_VPC_SIZE}"
            Write-Host "This is a test of the PowerShell action in GitHub Actions."

            $dataObj = @{
              GroupsToAdd = (${env:GROUPS_TO_ADD}.replace('\"', '"') | ConvertFrom-Json)
              GroupsToRemove = (${env:GROUPS_TO_REMOVE}.replace('\"', '"') | ConvertFrom-Json)
              UserPrincipalName = ${env:USER_PRINCIPAL_NAME}
            }

            $definitionJson = ${env:DEFINITION}
            $definitionObj = ConvertFrom-Json -InputObject $definitionJson

            Write-Host "Definition: $($definitionObj | ConvertTo-Json -Depth 10)"
            Write-Host "Data Object: $($dataObj | ConvertTo-Json -Depth 10)"
            Write-Host "Groups to Add: $($dataObj.GroupsToAdd | ConvertTo-Json -Depth 10)"

          azPSVersion: "latest"

      - name: calculate-terraform-environment
        id: calculate-terraform-environment
        env:
          WORKLOAD_SHORT_NAME: ${{ inputs.vend_workload_short_name }}
          ENVIRONMENT_TYPE: ${{ inputs.vend_environment_type }}
          ENVIRONMENT_NAME: ${{ inputs.vend_environment_name }}

        run: |
          vend_environment_name="$ENVIRONMENT_NAME"

          echo  "vend_workload_short_name "$WORKLOAD_SHORT_NAME""
          echo  "vend_environment_type "$ENVIRONMENT_TYPE""
          echo  "vend_environment_name "$ENVIRONMENT_NAME""


          terraformEnvironment=""$WORKLOAD_SHORT_NAME"-"$ENVIRONMENT_TYPE""

          if [[ -n "$ENVIRONMENT_NAME" ]];
          then
              terraformEnvironment=""$terraformEnvironment"-"$ENVIRONMENT_NAME""
          fi

          echo "terraformEnvironment: $terraformEnvironment"
          echo "terraformEnvironment=$terraformEnvironment" >> $GITHUB_OUTPUT

      - name: validate
        id: validate
        env:
          TITLE: ${{ inputs.vend_vpc_requestor }}
        run: |
          echo "Validating inputs..."

          echo "Workload Short Name: ${{ github.event.inputs.vend_workload_short_name }}"

          if [[ ! "${{ github.event.inputs.vend_workload_short_name }}" =~ ^[a-z]{3,6}$ ]]; then
            echo "Error: vend_workload_short_name must be between 3 and 6 characters long and all lowercase."
            exit 1
          fi

          echo "Environment Name: ${{ github.event.inputs.vend_environment_name }}"




          echo "VPC Requestor: "$TITLE""
          echo "VPC Requestor: "${{ github.event.inputs.vend_vpc_requestor }}""

      - name: Say hello
        id: say-hello
        run: |
          echo "Hello World"
