name: Test Validation of inputs

on:
  workflow_dispatch:
    inputs:
      vend_workload_short_name:
        description: Workload Short Name
        type: string
        required: true
      vend_environment_type:
        description: Environment Type
        type: choice
        required: true
        options:
          - Sandbox
          - Dev
          - Test
          - Preprod
          - Prod
          - Tooling
      vend_environment_name:
        description: Environment Name
        type: string
        required: false
      vend_roles:
        description: Roles
        type: string
        required: true
      vend_dns_sub_domain:
        description: DNS Sub Domains
        type: string
        required: false
      vend_ses_sub_domain:
        description: SES Sub Domains
        type: string
        required: false
      vend_vpc_size:
        description: VPC Size
        type: choice
        required: true
        options:
          - Small
          - Medium
          - Large
          - X-Large
      vend_vpc_requestor:
        description: VPC Requestor
        type: string
        required: true

jobs:
  First_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: validate
        id: validate
        run: |
          echo "Validating inputs..."

          echo "Workload Short Name: ${{ github.event.inputs.vend_workload_short_name }}"

          if [[ ! "${{ github.event.inputs.vend_workload_short_name }}" =~ ^[a-z]{3,6}$ ]]; then
            echo "Error: vend_workload_short_name must be between 3 and 6 characters long and all lowercase."
            exit 1
          fi

          echo "Environment Name: ${{ github.event.inputs.vend_environment_name }}"



          echo "Roles: ${{ github.event.inputs.vend_roles }}"

            if [[ -n "${{ github.event.inputs.vend_roles }}" && ! "${{ github.event.inputs.vend_roles }}" =~ ^[a-zA-Z0-9,]+$ ]]; then
            echo "Error: vend_roles must only contain alphanumeric characters or commas."
            exit 1
            fi

          echo "DNS Sub Domains: ${{ github.event.inputs.vend_dns_sub_domain }}"



          echo "SES Sub Domains: ${{ github.event.inputs.vend_ses_sub_domain }}"



          echo "VPC Requestor: ${{ github.event.inputs.vend_vpc_requestor }}"

      - name: Say hello
        id: say-hello
        run: |
          echo "Hello World"
