name: workflow dispatch test job

on:
  workflow_dispatch:
  push:

jobs:
  main-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: call workflow
        run: |
          echo "hello world"
