name: workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true

env:
  AWS_REGION: "eu-west-2"

permissions: write-all

jobs:
  main-run:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: call workflow
        run: |
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
